name: JSON parse

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"

jobs:
  test:
    name: setup and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 11
      - run: npm ci
      - run: npm test
